package com.ruzug.anidoroido.datatmp

import kotlin.random.Random

/**
 * SampleData for Jetpack Compose
 */
object SampleData {
    // Sample Anime List Data
    val simpleAnimeList = listOf(
        Anime(
            0,
            "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha ",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178869-qiEz0gQD8H5N.png"
        ),
        Anime(
            0,
            "Major 2nd",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100306-picxGtylsEST.jpg"
        ),
        Anime(
            0,
            "Flying Witch",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx76258-iHRY5gdGQ5HY.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha ",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178869-qiEz0gQD8H5N.png"
        ),
        Anime(
            0,
            "Major 2nd",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100306-picxGtylsEST.jpg"
        ),
        Anime(
            0,
            "Flying Witch",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx76258-iHRY5gdGQ5HY.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha ",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178869-qiEz0gQD8H5N.png"
        ),
        Anime(
            0,
            "Major 2nd",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100306-picxGtylsEST.jpg"
        ),
        Anime(
            0,
            "Flying Witch",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx76258-iHRY5gdGQ5HY.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha ",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178869-qiEz0gQD8H5N.png"
        ),
        Anime(
            0,
            "Major 2nd",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100306-picxGtylsEST.jpg"
        ),
        Anime(
            0,
            "Flying Witch",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx76258-iHRY5gdGQ5HY.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha ",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178869-qiEz0gQD8H5N.png"
        ),
        Anime(
            0,
            "Major 2nd",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100306-picxGtylsEST.jpg"
        ),
        Anime(
            0,
            "Flying Witch",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx76258-iHRY5gdGQ5HY.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha ",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178869-qiEz0gQD8H5N.png"
        ),
        Anime(
            0,
            "Major 2nd",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100306-picxGtylsEST.jpg"
        ),
        Anime(
            0,
            "Flying Witch",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx76258-iHRY5gdGQ5HY.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha ",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178869-qiEz0gQD8H5N.png"
        ),
        Anime(
            0,
            "Major 2nd",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100306-picxGtylsEST.jpg"
        ),
        Anime(
            0,
            "Flying Witch",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx76258-iHRY5gdGQ5HY.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha ",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178869-qiEz0gQD8H5N.png"
        ),
        Anime(
            0,
            "Major 2nd",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100306-picxGtylsEST.jpg"
        ),
        Anime(
            0,
            "Flying Witch",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx76258-iHRY5gdGQ5HY.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Clevatess: Majuu no Ou to Akago to Kabane no Yuusha ",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178869-qiEz0gQD8H5N.png"
        ),
        Anime(
            0,
            "Major 2nd",
            "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100306-picxGtylsEST.jpg"
        ),
        Anime(
            0,
            "Flying Witch",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx76258-iHRY5gdGQ5HY.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
        Anime(
            0,
            "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx86635-EdaLQmsn86Fy.png"
        ),
    )

    // Sample More Elaborated Anime List Data
    val animeList = listOf(
        Anime(
            id = 11759,
            name = "Accel World",
            episodes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx11759-o3ZRpFYnP5Lc.jpg",
        ),
        Anime(
            id = 13939,
            name = "Accel World EX",
            episodes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx13939-ZwDOMGMYUu4N.png",
        ),
        Anime(
            id = 21404,
            name = "Accel World = Infinite∞Burst",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21404-2jkb1Gidfb18.jpg",
        ),
        Anime(
            id = 21058,
            name = "Akagami no Shirayuki-hime",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21058-GRqasG1xk3bD.jpg",
        ),
        Anime(
            id = 21258,
            name = "Akagami no Shirayuki-hime 2nd Season",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21258-6UnmYMTMH0f7.jpg",
        ),
        Anime(
            id = 20613,
            name = "Akame ga Kill!",
            episodes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20613-HXHpec4bemk5.jpg",
        ),
        Anime(
            id = 20770,
            name = "Akatsuki no Yona",
            episodes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20770-brCDvhTXlums.png",
        ),
        Anime(
            id = 21138,
            name = "Akatsuki no Yona OVA",
            episodes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21138-zM8UHMGNp1tR.jpg",
        ),
        Anime(
            id = 20602,
            name = "Amagi Brilliant Park",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20602-f6CfipBF44kV.png",
        ),
        Anime(
            id = 15085,
            name = "AMNESIA",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx15085-GA9iJnPgjY1H.jpg",
        ),
        Anime(
            id = 6547,
            name = "Angel Beats!",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx6547-SYexAn5aFyss.png",
        ),
        Anime(
            id = 9062,
            name = "Angel Beats! Specials",
            episodes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx9062-x3XnEGxK4eqh.jpg",
        ),
        Anime(
            id = 9989,
            name = "Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.",
            episodes = 11,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx9989-hImMg6kCMm6I.jpg",
        ),
        Anime(
            id = 11111,
            name = "Another",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx11111-gvvE5bBYsyFo.png",
        ),
        Anime(
            id = 9919,
            name = "Ao no Exorcist",
            episodes = 25,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx9919-nXS7JOZrWHfS.jpg",
        ),
        Anime(
            id = 6166,
            name = "Asobi ni Iku yo!",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx6166-TzYLyxIl3a6i.png",
        ),
        Anime(
            id = 6347,
            name = "Baka to Test to Shoukanjuu",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx6347-DCSHLkCY7UT3.jpg",
        ),
        Anime(
            id = 8516,
            name = "Baka to Test to Shoukanjuu Ni!",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx8516-uAw5qWkceccn.jpg",
        ),
        Anime(
            id = 5081,
            name = "Bakemonogatari",
            episodes = 15,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx5081-9GocceQ5Z865.jpg",
        ),
        Anime(
            id = 20457,
            name = "Black Bullet",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20457-ftrNiYhZzgoY.jpg",
        ),
        Anime(
            id = 889,
            name = "BLACK LAGOON",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx889-4S7N2ciq2cwA.png",
        ),
        Anime(
            id = 4901,
            name = "BLACK LAGOON = Roberta's Blood Trail",
            episodes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx4901-evMxxc1A8pCF.jpg",
        ),
        Anime(
            id = 1519,
            name = "BLACK LAGOON = The Second Barrage",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx1519-cScqJxQW3LNL.png",
        ),
        Anime(
            id = 11633,
            name = "Blood Lad",
            episodes = 10,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx11633-vIjtabJq64Xt.jpg",
        ),
        Anime(
            id = 18441,
            name = "Blood Lad = Wagahai wa Neko de wa Nai",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx18441-UKhY0FflBETV.jpg",
        ),
        Anime(
            id = 21234,
            name = "Boku dake ga Inai Machi",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21234-XmqW39aQ9o7O.jpg",
        ),
        Anime(
            id = 1639,
            name = "Boku no Pico",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/1639.jpg",
        ),
        Anime(
            id = 10719,
            name = "Boku wa Tomodachi ga Sukunai",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx10719-aNf9gOOw62Fs.png",
        ),
        Anime(
            id = 14967,
            name = "Boku wa Tomodachi ga Sukunai NEXT",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx14967-ZGsclJ1xjPwr.jpg",
        ),
        Anime(
            id = 357,
            name = "Bokusatsu Tenshi Dokuro-chan",
            episodes = 4,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx357-k01dbafXBao6.jpg",
        ),
        Anime(
            id = 3389,
            name = "BUS GAMER",
            episodes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/3389.jpg",
        ),
        Anime(
            id = 1689,
            name = "Byousoku 5 Centimeter",
            episodes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx1689-rJKhjLEjQHSy.jpg",
        ),
        Anime(
            id = 12293,
            name = "Campione! = Matsurowanu Kamigami to Kamigoroshi no Maou",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx12293-DKc0XJ0cacSZ.jpg",
        ),
        Anime(
            id = 10578,
            name = "C³",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/b10578-Wv2VQQpSIsHA.jpg",
        ),
        Anime(
            id = 12505,
            name = "C³ Special",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/12505.jpg",
        ),
        Anime(
            id = 20997,
            name = "Charlotte",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20997-axVYrsIfjtYJ.jpg",
        ),
        Anime(
            id = 16157,
            name = "Choujigen Game Neptune THE ANIMATION",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx16157-GFIuj9e2Y8nK.jpg",
        ),
        Anime(
            id = 20472,
            name = "Choujigen Game Neptune THE ANIMATION = Yakusoku no Eien (True End),",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20472-Ywr8YyhaYTbU.png",
        ),
        Anime(
            id = 14741,
            name = "Chuunibyou demo Koi ga Shitai!",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx14741-CGXEIeUe2roA.jpg",
        ),
        Anime(
            id = 18671,
            name = "Chuunibyou demo Koi ga Shitai! Ren",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx18671-RVIY9TGd737H.jpg",
        ),
        Anime(
            id = 2167,
            name = "CLANNAD",
            episodes = 23,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx2167-pSDBcyc0vjej.jpg",
        ),
        Anime(
            id = 4181,
            name = "CLANNAD = After Story",
            episodes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx4181-zUKE7BZC62OF.png",
        ),
        Anime(
            id = 1575,
            name = "Code Geass = Hangyaku no Lelouch",
            episodes = 25,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx1575-hsmWM2ydNm1m.jpg",
        ),
        Anime(
            id = 2904,
            name = "Code Geass = Hangyaku no Lelouch R2",
            episodes = 25,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx2904-Fet9Q33suC7G.jpg",
        ),
        Anime(
            id = 21275,
            name = "Comet Lucifer",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21275-4XQkE1bTJvTk.png",
        ),
        Anime(
            id = 20806,
            name = "Cross Ange = Tenshi to Ryuu no Rondo",
            episodes = 25,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20806-TFTl8bavYzvc.jpg",
        ),
        Anime(
            id = 12549,
            name = "Dakara Boku wa, H ga Dekinai.",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx12549-GhbJO9KBUC7o.jpg",
        ),
        Anime(
            id = 2025,
            name = "DARKER THAN BLACK = Kuro no Keiyakusha",
            episodes = 25,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/b2025-ZKVteVzUyFLH.png",
        ),
        Anime(
            id = 7338,
            name = "DARKER THAN BLACK = Kuro no Keiyakusha - Gaiden",
            episodes = 4,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx7338-c6Uq5DmlEPVs.png",
        ),
        Anime(
            id = 6573,
            name = "DARKER THAN BLACK = Ryuusei no Gemini",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx6573-8D21dF6qwXQ2.png",
        ),
        Anime(
            id = 15583,
            name = "Date A Live",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx15583-Sxd2J4RJdRhj.jpg",
        ),
        Anime(
            id = 19163,
            name = "Date A Live II",
            episodes = 10,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/nx19163-eHXj3mNRaOXt.jpg",
        ),
        Anime(
            id = 20741,
            name = "Date A Live Movie = Mayuri Judgement",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20741-WdThAhseSo1y.jpg",
        ),
        Anime(
            id = 17641,
            name = "Date A Live = DATE TO DATE",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx17641-q5VVIoHcFZAZ.jpg",
        ),
        Anime(
            id = 20767,
            name = "Date A Live II = Kurumi Star Festival",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20767-kvu80j0CZx7C.png",
        ),
        Anime(
            id = 6880,
            name = "Deadman Wonderland",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx6880-qZ1jIqIYpST2.png",
        ),
        Anime(
            id = 1535,
            name = "DEATH NOTE",
            episodes = 37,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx1535-kUgkcrfOrkUM.jpg",
        ),
        Anime(
            id = 20931,
            name = "Death Parade",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/nx20931-bktYqOcxPERi.jpg",
        ),
        Anime(
            id = 552,
            name = "Digimon Adventure",
            episodes = 54,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx552-zad0ts5hylQJ.jpg",
        ),
        Anime(
            id = 1313,
            name = "Digimon Adventure 02",
            episodes = 50,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/nx1313-oCvzzU6fiCZB.png",
        ),
        Anime(
            id = 2398,
            name = "Digimon Adventure 02 = Diablomon no Gyakushuu",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/2398.jpg",
        ),
        Anime(
            id = 20802,
            name = "Digimon Adventure tri. 1 = Saikai",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20802-4fra401ry8FT.png",
        ),
        Anime(
            id = 21500,
            name = "Digimon Adventure tri. 2 = Ketsui",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21500-hC4Nhs2kNnZ3.png",
        ),
        Anime(
            id = 21596,
            name = "Digimon Adventure tri. 3 = Kokuhaku",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21596-KnjJA2qwVtdI.jpg",
        ),
        Anime(
            id = 2397,
            name = "Digimon Adventure = Bokura no War Game!",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx2397-jFhwpduFwf3r.jpg",
        ),
        Anime(
            id = 10155,
            name = "Dog Days",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx10155-e5d9PukNkE8D.jpg",
        ),
        Anime(
            id = 11783,
            name = "Dog Days'",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx11783-R9MxLofk3OH4.png",
        ),
        Anime(
            id = 20920,
            name = "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20920-MTREwZOG4BAD.jpg",
        ),
        Anime(
            id = 21660,
            name = "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka = Dungeon ni Onsen wo Motomeru no wa Machigatteiru Darou ka",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21660-ulujIFzucKf1.jpg",
        ),
        Anime(
            id = 226,
            name = "Elfen Lied",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx226-MibyRKhIrnTe.png",
        ),
        Anime(
            id = 2759,
            name = "Evangelion Shin Movie = Jo",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx2759-S0ATamQtDwlW.jpg",
        ),
        Anime(
            id = 3784,
            name = "Evangelion Shin Movie = Ha",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx3784-TGCsqLryKJ2R.jpg",
        ),
        Anime(
            id = 3785,
            name = "Evangelion Shin Movie = Kyuu",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx3785-a28lDzqtlfjB.png",
        ),
        Anime(
            id = 12565,
            name = "Fate/Prototype",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx12565-paVJhzp4BrF0.jpg",
        ),
        Anime(
            id = 356,
            name = "Fate/stay night",
            episodes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx356-mTpMvtillumS.png",
        ),
        Anime(
            id = 19603,
            name = "Fate/stay night = Unlimited Blade Works",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx19603-ycT0pyEgDVQu.jpg",
        ),
        Anime(
            id = 20792,
            name = "Fate/stay night = Unlimited Blade Works 2nd Season",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20792-Q53sZsUAh5FF.jpg",
        ),
        Anime(
            id = 10087,
            name = "Fate/Zero",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx10087-M4Hd9qrHGrXk.png",
        ),
        Anime(
            id = 11741,
            name = "Fate/Zero 2nd Season",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx11741-oEy1fJHYm2zJ.jpg",
        ),
        Anime(
            id = 5114,
            name = "Hagane no Renkinjutsushi = FULLMETAL ALCHEMIST",
            episodes = 64,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx5114-nSWCgQlmOMtj.jpg",
        ),
        Anime(
            id = 21156,
            name = "Fushigi na Somera-chan",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21156-lZI7sRPdnbg7.jpg",
        ),
        Anime(
            id = 20754,
            name = "Gakkou Gurashi!",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20754-e5JXeLpHoN7w.jpg",
        ),
        Anime(
            id = 21131,
            name = "Gakusen Toshi Asterisk",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21131-sh1HBXuF6qHH.jpg",
        ),
        Anime(
            id = 918,
            name = "Gintama",
            episodes = 201,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx918-iOaeBVUn4uK7.jpg",
        ),
        Anime(
            id = 7472,
            name = "Gintama = Shinyaku Benizakura-hen",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx7472-RveDgQsIZUNG.jpg",
        ),
        Anime(
            id = 15335,
            name = "Gintama = Kanketsu-hen - Yorozuya yo Eien Nare",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx15335-QjijwChGTBs0.png",
        ),
        Anime(
            id = 9969,
            name = "Gintama'",
            episodes = 51,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx9969-0GaRABYVdUcH.png",
        ),
        Anime(
            id = 15417,
            name = "Gintama' = Enchousen",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx15417-Uc2uNdWEixwi.jpg",
        ),
        Anime(
            id = 97889,
            name = "Gintama.",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx97889-ytqHdmus9wQi.jpg",
        ),
        Anime(
            id = 99714,
            name = "Gintama. = Porori-hen",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx99714-0pCKHe4XYIz7.jpg",
        ),
        Anime(
            id = 100784,
            name = "Gintama. = Shirogane no Tamashii-hen",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx100784-7fWdiduBFr95.jpg",
        ),
        Anime(
            id = 101925,
            name = "Gintama. = Shirogane no Tamashii-hen - Kouhan-sen",
            episodes = 14,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx101925-gcA84dgcSj2w.png",
        ),
        Anime(
            id = 20996,
            name = "Gintama°",
            episodes = 51,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20996-kBEGEGdeK1r7.jpg",
        ),
        Anime(
            id = 20849,
            name = "GOD EATER",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20849-TvJpY8iLEcYG.jpg",
        ),
        Anime(
            id = 10470,
            name = "GOD EATER Prologue",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/10470.jpg",
        ),
        Anime(
            id = 10793,
            name = "Guilty Crown",
            episodes = 22,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx10793-KCysCbrVNqK9.jpg",
        ),
        Anime(
            id = 21182,
            name = "Hacka Doll = THE Animation",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/21182-C6UGCr3h53nz.jpg",
        ),
        Anime(
            id = 21428,
            name = "Hai to Gensou no Grimgar",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21428-dFVIHeZ8McBe.jpg",
        ),
        Anime(
            id = 20593,
            name = "Hanamonogatari",
            episodes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20593-ri6S0Qt3mFkv.jpg",
        ),
        Anime(
            id = 20932,
            name = "Harmony",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20932-kw702YuhGeH5.jpg",
        ),
        Anime(
            id = 15809,
            name = "Hataraku Maou-sama!",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx15809-ECv3HyOYJKrk.jpg",
        ),
        Anime(
            id = 20881,
            name = "Heavy Object",
            episodes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20881-UqK6rR9vzRrw.jpg",
        ),
        Anime(
            id = 777,
            name = "HELLSING OVA",
            episodes = 10,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx777-F6547pSAR2Zd.jpg",
        ),
        Anime(
            id = 20912,
            name = "Hibike! Euphonium",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20912-SiiG4HPrjQlX.jpg",
        ),
        Anime(
            id = 21376,
            name = "Hibike! Euphonium = Kakedasu Monaka",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21376-MwAfybEhcdZf.jpg",
        ),
        Anime(
            id = 11617,
            name = "High School DxD",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/nx11617-nmxMU9Zh3H5R.jpg",
        ),
        Anime(
            id = 20745,
            name = "High School DxD BorN",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20745-HzWTPFv0P13I.jpg",
        ),
        Anime(
            id = 21573,
            name = "High School DxD BorN = Yomigaeranai Fushichou",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/21573-wp806EJfO602.jpg",
        ),
        Anime(
            id = 15451,
            name = "High School DxD NEW",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/nx15451-A5T54vmxUq9t.jpg",
        ),
        Anime(
            id = 21103,
            name = "High School DxD NEW OVA Oppai, Tsutsumimasu!",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/21103-iVibYXQ4Z4UF.jpg",
        ),
        Anime(
            id = 12729,
            name = "High School DxD OVA",
            episodes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/12729.jpg",
        ),
        Anime(
            id = 8074,
            name = "Gakuen Mokushiroku = HIGHSCHOOL OF THE DEAD",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx8074-YB63Ik96fjPj.png",
        ),
        Anime(
            id = 934,
            name = "Higurashi no Naku Koro ni",
            episodes = 26,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx934-wjMlVEl4CWwg.jpg",
        ),
        Anime(
            id = 1889,
            name = "Higurashi no Naku Koro ni Kai",
            episodes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx1889-NqhWV3QwBXZl.jpg",
        ),
        Anime(
            id = 20634,
            name = "Himegoto",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20634-2MlcIyiB3Eja.jpg",
        ),
        Anime(
            id = 9041,
            name = "IS = Infinite Stratos",
            episodes = 12,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx9041-nyIdVMM8q27K.jpg",
        ),
        Anime(
            id = 14719,
            name = "JoJo no Kimyou na Bouken (TV),",
            episodes = 26,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx14719-VT5dRzTBSZ0w.jpg",
        ),
        Anime(
            id = 21450,
            name = "JoJo no Kimyou na Bouken = Diamond wa Kudakenai",
            episodes = 39,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx21450-D7XFwEQjZ5GA.jpg",
        ),
        Anime(
            id = 20474,
            name = "JoJo no Kimyou na Bouken = Stardust Crusaders",
            episodes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20474-xuqem5GBlBtb.jpg",
        ),
        Anime(
            id = 20799,
            name = "JoJo no Kimyou na Bouken = Stardust Crusaders - Egypt-hen",
            episodes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx20799-S1eyqBDlx51E.jpg",
        ),
        Anime(
            id = 14467,
            name = "K",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx14467-TQjwOvq4jkYS.png",
        ),
        Anime(
            id = 5680,
            name = "K-ON!",
            episodes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx5680-r3AI3Cwfv0Aq.png",
        ),
        Anime(
            id = 9617,
            name = "K-ON! Movie",
            episodes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/anime/cover/small/bx9617-Z2RA1TIkcNEg.png",
        ),
    )

    // Sample Manga List Data
    val mangaList = listOf(
        Manga(
            id = 37519,
            name = "Kami nomi zo Shiru Sekai",
            chapters = 271,
            volumes = 26,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx37519-2A9eU21x8uVG.png",
        ),
        Manga(
            id = 56736,
            name = "Taiyou no Ie",
            chapters = 70,
            volumes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx56736-qYpc12PAQMxi.jpg",
        ),
        Manga(
            id = 82267,
            name = "Akuma no Riddle",
            chapters = 48,
            volumes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx82267-4ELeCvY8THHH.jpg",
        ),
        Manga(
            id = 65003,
            name = "Yamada-kun to 7-nin no Majo",
            chapters = 246,
            volumes = 28,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx65003-VU9hD7DFJrLj.jpg",
        ),
        Manga(
            id = 43949,
            name = "Medaka Box",
            chapters = 194,
            volumes = 22,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx43949-sSgW4VE0nQKH.jpg",
        ),
        Manga(
            id = 38144,
            name = "Sora no Otoshimono",
            chapters = 97,
            volumes = 20,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx38144-mPs2QWbRy2n3.jpg",
        ),
        Manga(
            id = 85856,
            name = "Cross Ange - Tenshi to Ryuu no Gakuen",
            chapters = 25,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/55856-dKI05TjnQP0B.png",
        ),
        Manga(
            id = 48597,
            name = "Sankarea",
            chapters = 59,
            volumes = 11,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx48597-LYYobBXEUav7.png",
        ),
        Manga(
            id = 31219,
            name = "Koudelka",
            chapters = 15,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/1219.jpg",
        ),
        Manga(
            id = 82007,
            name = "Choujigen Game Neptune: THE ANIMATION - Hello New World",
            chapters = 17,
            volumes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx82007-Pre79R7P3d8p.jpg",
        ),
        Manga(
            id = 76716,
            name = "Masamune-kun no Revenge",
            chapters = 54,
            volumes = 10,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx76716-wuf4DCyBf9aT.png",
        ),
        Manga(
            id = 53207,
            name = "Choujigen Game Neptune: Megami Tsuushin",
            chapters = 43,
            volumes = 4,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx53207-DQXD4oYqkXwc.jpg",
        ),
        Manga(
            id = 97553,
            name = "Jumyou wo Kaitotte Moratta. Ichinen ni Tsuki, Ichimanen de.",
            chapters = 18,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx97553-vqJj5DFS8v2p.jpg",
        ),
        Manga(
            id = 33102,
            name = "GIRL FRIENDS",
            chapters = 44,
            volumes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx33102-wPnSm6VVgpX9.jpg",
        ),
        Manga(
            id = 86719,
            name = "Shounen Shoujo",
            chapters = 16,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx86719-50Y6U7U5Meeo.jpg",
        ),
        Manga(
            id = 103687,
            name = "Yuusha Goikkou no Kaerimichi",
            chapters = 1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/103687-uLLcfSr9SFxv.png",
        ),
        Manga(
            id = 33083,
            name = "Suzumiya Haruhi no Yuuutsu",
            chapters = 9,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx33083-tlDz3pkPz1Mc.jpg",
        ),
        Manga(
            id = 80217,
            name = "Kami-sama ga Uso wo Tsuku.",
            chapters = 5,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx80217-QGyYpWc3qcpI.png",
        ),
        Manga(
            id = 117195,
            name = "[Oshi no Ko]",
            chapters = 168,
            volumes = 16,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx117195-r3kf8eF0xkDJ.png",
        ),
        Manga(
            id = 96775,
            name = "Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen Dai 1-bu - Hon ga Nai nara Tsukureba Ii!",
            chapters = 42,
            volumes = 7,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx96775-TFnKzz3A3Cnu.jpg",
        ),
        Manga(
            id = 105945,
            name = "Majo wa Mioji kara",
            chapters = 49,
            volumes = 7,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx105945-Y9IOXm4fVyEa.jpg",
        ),
        Manga(
            id = 86312,
            name = "Magi no Okurimono",
            chapters = 6,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/56312-wyKx8b6nWLRT.jpg",
        ),
        Manga(
            id = 85633,
            name = "philosophia",
            chapters = 6,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx85633-Qb9nJqeRuoRi.png",
        ),
        Manga(
            id = 102243,
            name = "Nidome no Natsu, Nidoto Aenai Kimi",
            chapters = 10,
            volumes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx102243-E4U3c7hO8nkj.jpg",
        ),
        Manga(
            id = 110926,
            name = "Bacouple",
            chapters = 12,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx110926-JPD5BwnoPuZk.jpg",
        ),
        Manga(
            id = 85138,
            name = "ib: Instant Bullet",
            chapters = 27,
            volumes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx85138-74SNsMS77eTC.jpg",
        ),
        Manga(
            id = 85412,
            name = "Shoujo Shuumatsu Ryokou",
            chapters = 47,
            volumes = 6,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx85412-wzZ2QFwbZJED.jpg",
        ),
        Manga(
            id = 138648,
            name = "Mishiranu Joshikousei ni Kankinsareta Mangaka no Hanashi",
            chapters = 33,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx138648-ZhymiY1NCRyS.png",
        ),
        Manga(
            id = 111297,
            name = "Rengoku no Toshi",
            chapters = 47,
            volumes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx111297-9BUwoXtsBdjb.jpg",
        ),
        Manga(
            id = 108258,
            name = "Akuyaku Reijou nano de Last Boss wo Kattemimashita",
            chapters = 21,
            volumes = 4,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx108258-suKnXRvj4AeY.png",
        ),
        Manga(
            id = 74489,
            name = "Houseki no Kuni",
            chapters = 108,
            volumes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx74489-5HtDCFfut8Be.jpg",
        ),
        Manga(
            id = 111970,
            name = "Sayonara Rose Garden",
            chapters = 18,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx111970-hpmPgZprtvI4.jpg",
        ),
        Manga(
            id = 111035,
            name = "Konyaku Haki Kara Hajimaru Akuyaku Reijou no Kangoku Slow Life",
            chapters = 3,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx111035-SM5kaQl7XIe0.png",
        ),
        Manga(
            id = 119076,
            name = "100-nichi Go ni Kao ni Deru Kashiwada",
            chapters = 100,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/b119076-i8kWPhHtin8K.jpg",
        ),
        Manga(
            id = 128150,
            name = "Kataude no Amy",
            chapters = 1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx128150-z6qfDrkKY6Wk.jpg",
        ),
        Manga(
            id = 130887,
            name = "Second Story Online: Risou no Majo Mezashite Ganbarimasu.",
            chapters = 2,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx130887-Q3EY0M7Bdj80.jpg",
        ),
        Manga(
            id = 116186,
            name = "Shounen no Abyss",
            chapters = 185,
            volumes = 18,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx116186-V270SY9BukUE.jpg",
        ),
        Manga(
            id = 102989,
            name = "Summer Time Render",
            chapters = 139,
            volumes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx102989-m8Dy8aSLcHLS.png",
        ),
        Manga(
            id = 105949,
            name = "Watashi Igai Jinrui Zenin Yuri",
            chapters = 11,
            volumes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx105949-wUmI4T2V92aL.jpg",
        ),
        Manga(
            id = 123067,
            name = "Majo ni Sasageru Trick",
            chapters = 31,
            volumes = 4,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx123067-fzE1fz6x9qSA.jpg",
        ),
        Manga(
            id = 99409,
            name = "Isekai Goumon Hime",
            chapters = 15,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx99409-H8Pa4PHDEn1K.jpg",
        ),
        Manga(
            id = 114627,
            name = "Ningen Fushin no Boukensha-tachi ga Sekai wo Sukuu you desu",
            chapters = 40,
            volumes = 6,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx114627-772yRcnXxgDE.jpg",
        ),
        Manga(
            id = 104869,
            name = "Aege-kai wo Wataru Hana-tachi",
            chapters = 12,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx104869-p3EkdTWodswo.png",
        ),
        Manga(
            id = 124382,
            name = "Hiraeth wa Tabiji no Hate",
            chapters = 17,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx124382-4jhg7kYxasf7.jpg",
        ),
        Manga(
            id = 102197,
            name = "1000-en Hero",
            chapters = 145,
            volumes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx102197-m7bMvMz6pbaA.jpg",
        ),
        Manga(
            id = 99559,
            name = "Nogi Wakaba wa Yuusha de Aru",
            chapters = 22,
            volumes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx99559-8uAOkOwpbe6I.png",
        ),
        Manga(
            id = 134367,
            name = "Majo ga Koisuru 5-byoumae",
            chapters = 4,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx134367-c04RfdOyqxIH.png",
        ),
        Manga(
            id = 146983,
            name = "Sayonara Eri",
            chapters = 1,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx146983-pLf4apCkFwKL.jpg",
        ),
        Manga(
            id = 149298,
            name = "Gaikotsu to Koi wa Dekiru no ka?",
            chapters = 1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx149298-9WeQYEC4J55I.jpg",
        ),
        Manga(
            id = 122683,
            name = "Shinrei Shashin-shi: Kouno Saburou",
            chapters = 1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx122683-Z5qOpImB3c1p.png",
        ),
        Manga(
            id = 98264,
            name = "Enidewi",
            chapters = 15,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx98264-VqDO7bShbsK0.jpg",
        ),
        Manga(
            id = 86770,
            name = "Totsukuni no Shoujo",
            chapters = 53,
            volumes = 11,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx86770-vjBM79Z1GVbs.jpg",
        ),
        Manga(
            id = 98023,
            name = "Museum",
            chapters = 28,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/98023-xty2lMkjICTJ.jpg",
        ),
        Manga(
            id = 114003,
            name = "Kakeochi Girl",
            chapters = 19,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx114003-NUIkHPN4ynIY.jpg",
        ),
        Manga(
            id = 102178,
            name = "Nabillera",
            chapters = 68,
            volumes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx102178-x8SqD1pBXsfu.jpg",
        ),
        Manga(
            id = 60079,
            name = "Annarasumanara",
            chapters = 28,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx60079-m0IndfC9eHAJ.png",
        ),
        Manga(
            id = 54561,
            name = "Kamisama no Iutoori",
            chapters = 21,
            volumes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx54561-R98YS8r4RUqy.jpg",
        ),
        Manga(
            id = 145590,
            name = "Suzumiya Haruhi no Tameiki",
            chapters = 7,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx145590-4NW8DCzRO4LA.jpg",
        ),
        Manga(
            id = 145591,
            name = "Suzumiya Haruhi no Taikutsu",
            chapters = 5,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx145591-W4qVzuBu3nje.jpg",
        ),
        Manga(
            id = 145592,
            name = "Suzumiya Haruhi no Shoushitsu",
            chapters = 8,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx145592-irNg07taJU5j.jpg",
        ),
        Manga(
            id = 145593,
            name = "Suzumiya Haruhi no Bousou",
            chapters = 6,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx145593-pB0gWJ8WzdeZ.jpg",
        ),
        Manga(
            id = 145594,
            name = "Suzumiya Haruhi no Douyou",
            chapters = 5,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx145594-wURR2hX2HMkg.jpg",
        ),
        Manga(
            id = 145595,
            name = "Suzumiya Haruhi no Inbou",
            chapters = 9,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx145595-pTKzikdD5c4j.jpg",
        ),
        Manga(
            id = 127078,
            name = "Hei no Naka no Biyoushitsu",
            chapters = 5,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx127078-5q5XmaK9FgMj.png",
        ),
        Manga(
            id = 97852,
            name = "Komi-san wa, Komyushou desu.",
            chapters = 537,
            volumes = 37,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx97852-M7vlc2OGR2gp.jpg",
        ),
        Manga(
            id = 104763,
            name = "Nande Ikiteru ka Wakaranai Hito: Izumi Sumi 25-sai",
            chapters = 28,
            volumes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx104763-ydvRIO9GKc4A.jpg",
        ),
        Manga(
            id = 100801,
            name = "Hana ni Arashi",
            chapters = 162,
            volumes = 13,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx100801-94JFvdg8Sk9c.jpg",
        ),
        Manga(
            id = 97703,
            name = "Seito Kaichou desu ga Josou Hajimemashita",
            chapters = 19,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx97703-pfxxzDOljBjE.jpg",
        ),
        Manga(
            id = 98741,
            name = "Majo no Tabitabi",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx98741-O0Xcc89Id03h.jpg",
        ),
        Manga(
            id = 105913,
            name = "Majo no Tabitabi",
            chapters = 24,
            volumes = 6,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx105913-A0w5OohVRfjb.jpg",
        ),
        Manga(
            id = 107980,
            name = "Chichi wa Eiyuu, Haha wa Seirei, Musume no Watashi wa Tenseisha.",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx107980-nA99veQeNpoA.png",
        ),
        Manga(
            id = 142994,
            name = "Mishiranu Joshikousei ni Isourousareta Mangaka no Hanashi",
            chapters = 15,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx142994-9gXrJ3KegWwR.jpg",
        ),
        Manga(
            id = 30004,
            name = "Yokohama Kaidashi Kikou",
            chapters = 142,
            volumes = 14,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/b30004-k0YUnO94IB4x.jpg",
        ),
        Manga(
            id = 118586,
            name = "Sousou no Frieren",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx118586-CXKgWikBFQgS.jpg",
        ),
        Manga(
            id = 51525,
            name = "Akatsuki no Yona",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx51525-wZ1AjkbXrKns.png",
        ),
        Manga(
            id = 101131,
            name = "Toshokan no Daimajutsushi",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx101131-u4iK3v1VvfLq.jpg",
        ),
        Manga(
            id = 76258,
            name = "Flying Witch",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx76258-iHRY5gdGQ5HY.png",
        ),
        Manga(
            id = 126933,
            name = "Akuyaku Reijou desu ga, Heroine ni Kouryaku Saretemasu wa!? Anthology Comic",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx126933-Hv70FBSILwnw.png",
        ),
        Manga(
            id = 102907,
            name = "Kao ni Denai Kashiwada-san to Kao ni Deru Oota-kun",
            chapters = 135,
            volumes = 10,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx102907-1EUr4KPzBmaP.jpg",
        ),
        Manga(
            id = 111149,
            name = "Yozakura-san Chi no Daisakusen",
            chapters = 259,
            volumes = 29,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx111149-cHYBsPbWIb3L.jpg",
        ),
        Manga(
            id = 132029,
            name = "Dandadan",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx132029-prGF4gePdSKv.jpg",
        ),
        Manga(
            id = 122063,
            name = "Shangri-La Frontier: Kusoge Hunter, Kami ge ni Idoman to su",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx122063-j2wIvwb6yzPM.jpg",
        ),
        Manga(
            id = 33014,
            name = "Touhou Bougetsushou: Silent Sinner in Blue",
            chapters = 21,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/b33014-qQTnfnkgN8g5.jpg",
        ),
        Manga(
            id = 123458,
            name = "Shuumatsu Touring",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx123458-Vjer1KnNMBpI.jpg",
        ),
        Manga(
            id = 86635,
            name = "Kaguya-sama wa Kokurasetai: Tensaitachi no Renai Zunousen",
            chapters = 281,
            volumes = 28,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx86635-EdaLQmsn86Fy.png",
        ),
        Manga(
            id = 101449,
            name = "Kuma Kuma Kuma Bear",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx101449-k7TupMYKOCgx.png",
        ),
        Manga(
            id = 167423,
            name = "Noa-senpai wa Tomodachi.",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx167423-YntPE72Qy0xz.jpg",
        ),
        Manga(
            id = 139122,
            name = "Youhei to Shousetsuka",
            chapters = 19,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx139122-QtBOjWZpsFJ3.jpg",
        ),
        Manga(
            id = 99536,
            name = "Munou na Nana",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx99536-Ad0c9WNX50L6.jpg",
        ),
        Manga(
            id = 30002,
            name = "Berserk",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx30002-Cul4OeN7bYtn.jpg",
        ),
        Manga(
            id = 106654,
            name = "Samurai 8: Hachimaruden",
            chapters = 43,
            volumes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx106654-bkVZEwY0m8o9.jpg",
        ),
        Manga(
            id = 74167,
            name = "Gekkou",
            chapters = 11,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx74167-vZBrFyAV7Kyt.jpg",
        ),
        Manga(
            id = 98867,
            name = "Ame no Hi no Iris: Boku no Shukudai",
            chapters = 1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/98867-ZQqPxUYSm5IC.jpg",
        ),
        Manga(
            id = 72879,
            name = "Hana to Rakurai",
            chapters = 10,
            volumes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx72879-VGRh4Y6yF1Zj.jpg",
        ),
        Manga(
            id = 107534,
            name = "Oujo Denka wa Oikari no You desu",
            chapters = 77,
            volumes = 9,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx107534-vdqlb1xXDtPY.jpg",
        ),
        Manga(
            id = 124591,
            name = "Riviere to Inori no Kuni",
            chapters = 9,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx124591-9YN1gHcZcGS7.jpg",
        ),
        Manga(
            id = 44065,
            name = "Yumekui Merry",
            chapters = 141,
            volumes = 24,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx44065-8HPpg3r3WP5Q.png",
        ),
        Manga(
            id = 68105,
            name = "Kase-san Series",
            chapters = 25,
            volumes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx68105-BzzbeASA2vGP.jpg",
        ),
        Manga(
            id = 113533,
            name = "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx113533-u3D4i0jHzt2z.jpg",
        ),
        Manga(
            id = 109895,
            name = "Maya-san no Yofukashi",
            chapters = 39,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx109895-395AddJmHcax.png",
        ),
        Manga(
            id = 86218,
            name = "Yagate Kimi ni Naru",
            chapters = 53,
            volumes = 8,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx86218-sIl9tnqHZQyh.jpg",
        ),
        Manga(
            id = 67109,
            name = "Yokokuhan",
            chapters = 22,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/37109.jpg",
        ),
        Manga(
            id = 106758,
            name = "Kage no Jitsuryokusha ni Naritakute!",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx106758-jtXpQYQqyNJv.jpg",
        ),
        Manga(
            id = 85247,
            name = "Sousei no Onmyouji",
            chapters = 142,
            volumes = 35,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx85247-ViNailSUKZVn.jpg",
        ),
        Manga(
            id = 98263,
            name = "Tongari Boushi no Atelier",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx98263-kIeaTXrAbGkj.jpg",
        ),
        Manga(
            id = 52900,
            name = "Fractale",
            chapters = 13,
            volumes = 3,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/22900.jpg",
        ),
        Manga(
            id = 33728,
            name = "Natsu no Arashi!",
            chapters = 50,
            volumes = 8,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/3728.jpg",
        ),
        Manga(
            id = 104881,
            name = "Akuma no Mama",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx104881-BUTluV6Xb5LM.jpg",
        ),
        Manga(
            id = 122344,
            name = "Tensei Oujo to Tensai Reijou no Mahou Kakumei",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx122344-NUecmoX09FTw.jpg",
        ),
        Manga(
            id = 30731,
            name = "EDEN: It's an Endless World!",
            chapters = 131,
            volumes = 18,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx30731-I2lMIZYDECe2.jpg",
        ),
        Manga(
            id = 128896,
            name = "Witch Watch",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx128896-VJfCBLFkm4Lb.jpg",
        ),
        Manga(
            id = 143662,
            name = "Shoujo☆Kageki Revue Starlight Comic Anthology: Nine Stories",
            chapters = 9,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx143662-CzgmAnLpfSPm.jpg",
        ),
        Manga(
            id = 123777,
            name = "Watashi wo Tabetai, Hitodenashi",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx123777-sdb3Fts3FlVH.jpg",
        ),
        Manga(
            id = 167649,
            name = "Academy Cheonjaekaljabi",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx167649-8qpdNIjBdIhQ.png",
        ),
        Manga(
            id = 151202,
            name = "Share House Nile",
            chapters = 20,
            volumes = 4,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx151202-JhlX4xDtQTPK.png",
        ),
        Manga(
            id = 117620,
            name = "Kimi to Tsuzuru Utakata",
            chapters = 32,
            volumes = 6,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx117620-cyvy8nO9GLm8.jpg",
        ),
        Manga(
            id = 154705,
            name = "Kyou mo Veranda de",
            chapters = 90,
            volumes = 7,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx154705-wVRfcSRwNvdc.jpg",
        ),
        Manga(
            id = 85926,
            name = "Ame no Hi no Iris",
            chapters = 5,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx85926-86Fgpjd7IYXd.png",
        ),
        Manga(
            id = 100164,
            name = "Ikenie Touhyou",
            chapters = 69,
            volumes = 7,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx100164-I9HT4XfMGD4h.jpg",
        ),
        Manga(
            id = 163923,
            name = "Isshou Senkin",
            chapters = -1,
            volumes = -1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/b163923-e22pT1gepB0N.jpg",
        ),
        Manga(
            id = 30201,
            name = "Kidou Keisatsu Patlabor",
            chapters = 269,
            volumes = 22,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx30201-iNTIsTRTrx4R.png",
        ),
        Manga(
            id = 142568,
            name = "Takopii no Genzai",
            chapters = 16,
            volumes = 2,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx142568-xPC5wQPxTV1s.jpg",
        ),
        Manga(
            id = 85538,
            name = "Kimi to Nadekko!",
            chapters = 3,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/b85538-qTUEO4sYAwQW.jpg",
        ),
        Manga(
            id = 106726,
            name = "Shimeji Simulation",
            chapters = 49,
            volumes = 5,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx106726-VaixYIRrOFu8.jpg",
        ),
        Manga(
            id = 42200,
            name = "High School Musical",
            chapters = -1,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/n42200-A1ytGvoDswfx.png",
        ),
        Manga(
            id = 41734,
            name = "Watashitachi no Shiawase na Jikan",
            chapters = 8,
            volumes = 1,
            imageUrl = "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/11734.jpg",
        )
    )

    // Preloaded categories
    val categories = listOf(
        Category("Watching", false),
        Category("Completed", false),
        Category("Paused", false),
        Category("Dropped", false),
        Category("Plan To Watch", false),
    )

    // Sample UserMedia Anime List Data
    val userMediaListAnime = animeList.map { anime ->
        val category = categories.random()
        UserMedia(
            score = if (category.name == "Completed" || category.name == "Watching") Random.nextFloat() * 10 else null,
            category = category,
            progress = if (category.name == "Completed") anime.episodes else if (category.name == "Plan To Watch") 0 else Random.nextInt(0, anime.episodes),
            media = anime
        )
    }

    // Sample UserMedia Manga List Data
    val userMediaListManga = mangaList.map { manga ->
        val category = categories.random()
        UserMedia(
            score = if (category.name == "Completed" || category.name == "Watching") Random.nextFloat() * 10 else null,
            category = category,
            progress = if (category.name == "Completed") manga.chapters else if (category.name == "Plan To Watch") 0 else Random.nextInt(0, manga.chapters.takeIf { it > 0 }?:100),
            progressVolumes = if (category.name == "Completed") manga.volumes else if (category.name == "Plan To Watch") 0 else Random.nextInt(0, manga.volumes.takeIf { it > 0 }?:100),
            media = manga
        )
    }
}