name: Android Testing CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Check lint
        run: ./gradlew lint

      - name: Upload lint reports (HTML)
        uses: actions/upload-artifact@v6
        with:
          name: lint-reports
          path: 'app/build/reports/lint-results-debug.html'